# on: pull_request
on: push
jobs:
    Linting:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Install pylint
          run: sudo apt update && sudo apt install pylint
        - name: Linting
          run: pylint *.py
        - name: Unit testing
          run: python3 test.py
        
        # - name: Lint
        # uses: gabriel-milan/action-pylint@v1
        # with:
        #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # GitHub token
        #     path: "./*.py" # Glob pattern for files to lint
        #     fail: true # Fail the action if pylint errors are found
        #     pr-message: true # Send a PR message if pylint errors are found

# .github/workflows/cd_production.yml
# name: Deploy to Production
# on:
#   push:
#     branches: [ main ]
# jobs:
#   build_and_test:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - name: Use Node.js
#       uses: actions/setup-node@v1
#       with:
#         node-version: 12
#     - name: Install Dependencies
#       run: npm ci
#     - name: Run Tests
#       run: npm test
#   deploy:
#     needs: build_and_test
#     runs-on: ubuntu-latest
#     steps:
#     - name: Deploy to Production
#       uses: Azure/webapps-deploy@v2
#       with:
#         app-name: 'your-app-name'
#         slot-name: 'production'
#         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
#         package: .